package common

const (
	FalconContainerInjection                = "sensor.falcon-system.crowdstrike.com/injection"
	FalconContainerInjectorTLSName          = "injector-tls"
	FalconHostInstallDir                    = "/opt"
	FalconInitHostInstallDir                = "/host_opt"
	FalconDataDir                           = "/opt/CrowdStrike"
	FalconInitDataDir                       = "/host_opt/CrowdStrike/"
	FalconConfigDir                         = "/opt/Crowdstrike/config"
	FalconStoreFile                         = "/opt/CrowdStrike/falconstore"
	FalconInitStoreFile                     = "/host_opt/CrowdStrike/falconstore"
	FalconDaemonsetInitBinary               = "/opt/CrowdStrike/falcon-daemonset-init -i"
	FalconDaemonsetConfigureClusterIdBinary = "/opt/CrowdStrike/configure-cluster-id"
	FalconDaemonsetCleanupBinary            = "/opt/CrowdStrike/falcon-daemonset-init -u"
	FalconDaemonsetBinary                   = "/opt/CrowdStrike/falcon-daemonset-init"
	FalconContainerProbePath                = "/live"
	FalconAdmissionClientStartupProbePath   = "/startz"
	FalconAdmissionClientLivenessProbePath  = "/livez"
	FalconAdmissionStartupProbePath         = "/startz-kac"
	FalconAdmissionLivenessProbePath        = "/livez-kac"
	FalconAdmissionServiceHTTPSName         = "webhook-port"
	FalconServiceHTTPSName                  = "https"
	FalconServiceHTTPSPort                  = 443
	FalconAdmissionWatcherPortName          = "watcher-health"
	FalconAdmissionWatcherPort              = int32(4080)
	FalconAdmissionValidatingWebhookName    = "validating.admission.falcon.crowdstrike.com"
	FalconAdmissionClusterNameConfigMapName = "falcon-kac-meta"
	FalconAdmissionComponentName            = "kac"
	FalconAdmissionServiceApp               = "falcon-kac"
	FalconImageAnalyzerComponentName        = "iar"
	FalconImageAnalyzerAgentService         = "iar-agent-service"
	FalconImageAnalyzerAgentServiceApp      = "falcon-image-analyzer"
	FalconImageAnalyzerAgentServicePort     = 443
	FalconImageAnalyzerAgentServicePortName = "service-port"

	AppLabelKey              = "app"
	KubernetesComponentKey   = "app.kubernetes.io/component"
	KubernetesNameKey        = "app.kubernetes.io/name"
	FalconInstanceNameKey    = "crowdstrike.com/name"
	FalconInstanceKey        = "crowdstrike.com/instance"
	FalconComponentKey       = "crowdstrike.com/component"
	FalconManagedByKey       = "crowdstrike.com/managed-by"
	FalconPartOfKey          = "crowdstrike.com/part-of"
	FalconProviderKey        = "crowdstrike.com/provider"
	FalconCreatedKey         = "crowdstrike.com/created-by"
	FalconAdmissionReviewKey = "falcon.crowdstrike.com/admission-review"

	FalconKernelSensor        = "kernel_sensor"
	FalconSidecarSensor       = "container_sensor"
	FalconAdmissionController = "admission_controller"
	FalconImageAnalyzer       = "falcon-imageanalyzer"
	FalconCloudGuard          = "falcon-cloudguard"
	FalconFinalizer           = "falcon.crowdstrike.com/finalizer"
	FalconProviderValue       = "crowdstrike"
	FalconPartOfValue         = "Falcon"
	FalconCreatedValue        = "falcon-operator"
	FalconManagedByValue      = "controller-manager"
	FalconPriorityClassName   = "system-cluster-critical"

	SidecarServiceAccountName   = "falcon-operator-sidecar-sensor"
	FalconPullSecretName        = "crowdstrike-falcon-pull-secret"
	NodeServiceAccountName      = "falcon-operator-node-sensor"
	AdmissionServiceAccountName = "falcon-operator-admission-controller"
	NodeClusterRoleBindingName  = "falcon-operator-node-sensor-rolebinding"
	ImageServiceAccountName     = "falcon-operator-image-analyzer"

	CloudGuardServiceAccountName      = "falcon-clusterguard-sa"
	CloudGuardDeploymentName          = "falcon-clusterguard"
	CloudGuardConfigMapName           = "falcon-clusterguard-config"
	CloudGuardClusterRoleName         = "falcon-clusterguard-resource-reader"
	CloudGuardClusterRoleBindingName  = "falcon-clusterguard-security-crb"
	CloudGuardRoleName                = "falcon-clusterguard-role"
	CloudGuardRoleBindingName         = "falcon-clusterguard-rolebinding"
	CloudGuardWebhookServiceName      = "webhook"
	CloudGuardAPIServiceName          = "api"
	CloudGuardWebhookPort             = int32(4443)
	CloudGuardWebhookPortStr          = "4443"
	CloudGuardGRPCPort                = int32(50051)
	CloudGuardGRPCPortStr             = "50051"
	CloudGuardWatcherHTTPPort         = int32(4080)
	CloudGuardWatcherHTTPPortStr      = "4080"
	CloudGuardTLSSecretName           = "falcon-clusterguard-tls"
	CloudGuardAPITLSSecretName        = "falcon-api-tls"
	CloudGuardAPICASecretName         = "falcon-api-ca"
	CloudGuardSensorTLSSecretName     = "falcon-sensor-tls"
	CloudGuardValidatingWebhookName   = "validating.falcon-kac.crowdstrike.com"
	CloudGuardComponentName           = "ksp"

	CloudGuardSensorServiceAccountName     = "crowdstrike-falcon-sa"
	CloudGuardSensorConfigMapName          = "falcon-sensor-config"
	CloudGuardSensorClusterRoleBindingName = "falcon-sensor-access-binding"
	CloudGuardSensorClusterRoleName        = "falcon-sensor-access-role"
	CloudGuardSensorDaemonSetName          = "falcon-sensor"
	CloudGuardSensorCleanupServiceAccountName = "crowdstrike-falcon-sa-node-cleanup"
	CloudGuardSensorCleanupDaemonSetName      = "falcon-sensor-node-cleanup"

	// GKE Autopilot requires names to have an exact match for WorkloadAllowlists
	GKEAutoPilotConfigMapName           = "falcon-node-sensor-config"
	GKEAutoPilotAllowListLabelKey       = "cloud.google.com/matching-allowlist"
	GKEAutoPilotDeployDSAllowlistPrefix = "crowdstrike-falconsensor-deploy-allowlist"
	GKEAutoPilotCleanupAllowlistPrefix  = "crowdstrike-falconsensor-cleanup-allowlist"
)
